import React,{useEffect,useState} from 'react';
import {Link,NavLink,Navigate,Route,Routes,useNavigate,useParams} from 'react-router-dom';
import {connect,contractAddress,loadReviews,write,type Match,type Review} from './chain';

const states=['','Pending','Evaluated','Authorized','Consumed','Unresolved','Cancelled'];
const verdicts=['','Clear','Disclosed conflict','Undisclosed conflict','Insufficient evidence'];
const short=(v:string)=>v?`${v.slice(0,8)}…${v.slice(-6)}`:'—';
type Data={reviews:Review[];matches:Record<number,Match[]>;total:number};
type Ctx={data:Data|null;wallet:string;run:(m:string,a:(string|number)[])=>Promise<void>;refresh:()=>Promise<void>};

function Frame({children,wallet,onConnect,status}:{children:React.ReactNode;wallet:string;onConnect:()=>void;status:string}){
 return <><header><Link className="brand" to="/"><img className="brand-logo" src="/mandate-glass-logo.png" alt="Mandate Glass"/><span><b>Mandate Glass</b><small>Delegate disclosure registry</small></span></Link><nav><NavLink to="/">Briefing</NavLink><NavLink to="/new">Open review</NavLink><NavLink to="/reviews">Registry</NavLink></nav><button className="wallet" onClick={onConnect}>{wallet?short(wallet):'Connect wallet'}</button></header><div className="ticker"><span>STUDIONET</span><span>{status}</span><span>{contractAddress?short(contractAddress):'CONTRACT NOT DEPLOYED'}</span></div><main>{children}</main><footer>Canonical evidence · bounded acquisition · single-use authorization</footer></>;
}
function Home({data}:{data:Data|null}){const unresolved=data?.reviews.filter(r=>r.state===5).length??0;return <section className="home"><p className="eyebrow">Governance integrity desk / Issue 01</p><h1>See the interests<br/><i>behind the vote.</i></h1><p className="lede">A narrow GenLayer gate that checks a DAO delegate’s disclosure against canonical proposal recipients and an authority-maintained affiliation registry.</p><div className="metrics"><article><b>{data?.total??'—'}</b><span>reviews registered</span></article><article><b>{unresolved}</b><span>need evidence retry</span></article><article><b>3-way</b><span>canonical source binding</span></article></div><div className="split"><div><h2>Why an Intelligent Contract?</h2><p>Validators independently acquire one locked GitHub snapshot, verify every blob, and resolve semantic organization aliases that bytecode cannot understand.</p></div><div className="rule"><b>No contributor URLs.</b><b>No declared digest trust.</b><b>No authorization on hidden conflicts.</b></div></div></section>}
function NewReview({wallet,run}:{wallet:string;run:Ctx['run']}){const nav=useNavigate();const [f,setF]=useState({repository:'',commit:'',proposal:'proposal.json',registry:'affiliations.json',disclosure:'disclosure.json',proposalId:'',delegate:'',policy:'Active affiliations matching a funded recipient must be disclosed.',deadline:''});const change=(k:string,v:string)=>setF({...f,[k]:v});async function submit(e:React.FormEvent){e.preventDefault();const deadline=Math.floor(new Date(f.deadline).getTime()/1000);await run('create_review',[f.repository,f.commit,f.proposal,f.registry,f.disclosure,f.proposalId,f.delegate,f.policy,deadline]);nav('/reviews');}return <section><p className="eyebrow">New docket</p><h1 className="page-title">Open a disclosure review</h1><form onSubmit={submit} className="paper-form"><label>GitHub repository<input value={f.repository} onChange={e=>change('repository',e.target.value)} placeholder="owner/repository" required/></label><label>Locked snapshot commit<input value={f.commit} onChange={e=>change('commit',e.target.value)} minLength={40} maxLength={40} required/></label><div className="three"><label>Proposal document<input value={f.proposal} onChange={e=>change('proposal',e.target.value)} required/></label><label>Affiliation registry<input value={f.registry} onChange={e=>change('registry',e.target.value)} required/></label><label>Delegate disclosure<input value={f.disclosure} onChange={e=>change('disclosure',e.target.value)} required/></label></div><div className="two"><label>Proposal ID<input value={f.proposalId} onChange={e=>change('proposalId',e.target.value)} required/></label><label>Delegate address<input value={f.delegate} onChange={e=>change('delegate',e.target.value)} required/></label></div><label>Locked policy<textarea value={f.policy} onChange={e=>change('policy',e.target.value)} required/></label><label>Vote deadline<input type="datetime-local" value={f.deadline} onChange={e=>change('deadline',e.target.value)} required/></label><button className="primary" disabled={!wallet}>Register immutable review</button>{!wallet&&<small>Connect the DAO creator wallet before submitting.</small>}</form></section>}
function Registry({data}:{data:Data|null}){return <section><p className="eyebrow">Public ledger</p><h1 className="page-title">Disclosure review registry</h1><div className="table">{data?.reviews.length?data.reviews.slice().reverse().map(r=><Link to={`/review/${r.review_id}`} className="row" key={r.review_id}><b>#{String(r.review_id).padStart(3,'0')}</b><span>{r.proposal_id}<small>{r.repository}</small></span><span>{short(r.delegate)}</span><em className={`state s${r.state}`}>{states[r.state]}</em></Link>):<div className="empty">No on-chain reviews found.</div>}</div></section>}
function Detail({data,run}:{data:Data|null;run:Ctx['run']}){const id=Number(useParams().id);const r=data?.reviews.find(x=>x.review_id===id);if(data&&!r)return <Navigate to="/reviews"/>;if(!r)return <div className="loading">Reading verified record…</div>;const rows=data?.matches[id]??[];return <section><p className="eyebrow">Docket #{id}</p><div className="detail-head"><h1 className="page-title">{r.proposal_id}</h1><em className={`state s${r.state}`}>{states[r.state]}</em></div><div className="facts"><div><small>Delegate</small><b>{r.delegate}</b></div><div><small>Snapshot</small><b>{short(r.snapshot_commit)}</b></div><div><small>Verdict</small><b>{verdicts[r.verdict]}</b></div><div><small>Revision</small><b>{r.revision}</b></div></div><article className="digest"><small>Evidence commitment</small><code>{r.evidence_digest||'Not produced yet'}</code></article>{rows.map((m,i)=><article className="match" key={i}><b>{m.organization}</b><span>{m.role} · recipient {m.recipient_id}</span><em>{m.disclosed?'Disclosed':'Not disclosed'}</em></article>)}<div className="actions">{(r.state===1||r.state===5)&&<button className="primary" onClick={()=>run(r.state===5?'retry_review':'evaluate_review',[id,r.revision])}>{r.state===5?'Retry acquisition':'Evaluate evidence'}</button>}{r.state===2&&r.verdict<3&&<button className="primary" onClick={()=>run('authorize_result',[id,r.revision])}>Authorize result</button>}{r.state===3&&<button className="primary" onClick={()=>run('consume_authorization',[id,r.revision])}>Consume authorization</button>}{r.state===1&&<button className="quiet" onClick={()=>run('cancel_pending',[id])}>Cancel pending review</button>}</div></section>}
export function App(){const [wallet,setWallet]=useState('');const [data,setData]=useState<Data|null>(null);const [status,setStatus]=useState('INITIALIZING CANONICAL READER');const [error,setError]=useState('');async function refresh(){if(!contractAddress){setStatus('AWAITING VERIFIED DEPLOYMENT');return;}setStatus('READING ON-CHAIN REGISTRY');try{setData(await loadReviews());setError('');setStatus('REGISTRY VERIFIED');}catch(e){setError(String(e));setStatus('READ FAILED');}}useEffect(()=>{void refresh()},[]);async function run(method:string,args:(string|number)[]){if(!wallet)throw new Error('Connect wallet first.');setStatus(`AWAITING ${method.toUpperCase()}`);try{const hash=await write(method,args,wallet);setStatus(`FINALIZED ${short(hash)}`);await refresh();}catch(e){setError(String(e));setStatus('TRANSACTION FAILED');throw e;}}return <Frame wallet={wallet} onConnect={()=>connect().then(setWallet).catch(e=>setError(String(e)))} status={status}>{error&&<div className="error">{error}<button onClick={()=>void refresh()}>Retry read</button></div>} {!data&&contractAddress&&<div className="loading"><span></span>Acquiring verified registry state…</div>}<Routes><Route path="/" element={<Home data={data}/>}/><Route path="/new" element={<NewReview wallet={wallet} run={run}/>}/><Route path="/reviews" element={<Registry data={data}/>}/><Route path="/review/:id" element={<Detail data={data} run={run}/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes></Frame>}
