import React,{useEffect,useState}from'react';
import{connect,contractAddress,loadGovernance,write,type Dao,type Proposal,type Review,type Vote}from'./chain';
const states=['','Pending','Evaluated','Authorized','Consumed','Unresolved'];const verdicts=['','Clear','Disclosed conflict','Undisclosed conflict','Insufficient evidence'];const short=(v:string)=>v?`${v.slice(0,8)}…${v.slice(-6)}`:'—';
type Data={counts:{daos:number;proposals:number;reviews:number;votes:number};daos:Dao[];proposals:Proposal[];reviews:Review[];votes:Vote[]};
export function walletChanged(connected:string,current:string){return connected.toLowerCase()!==current.toLowerCase()}
export function executionBlockReason(r:Review,p:Proposal,now:number,account=r.delegate,expectedRevision=r.revision){if(walletChanged(r.delegate,account))return'ACCOUNT_CHANGED';if(expectedRevision!==r.revision)return'STALE_REVISION';if(r.state===5)return'UNRESOLVED_EVIDENCE';if(r.state!==3||r.authorization_consumed)return'NOT_AUTHORIZED';if(!p.open||Number(p.deadline)<now)return'VOTE_WINDOW_CLOSED';if(!r.authorization_scope)return'SCOPE_MISSING';return''}
export function mayExecute(r:Review,p:Proposal,now:number){return executionBlockReason(r,p,now)===''}
function Input({label,...p}:any){return <label>{label}<input {...p}/></label>}
export function App(){const[wallet,setWallet]=useState('');const[data,setData]=useState<Data|null>(null);const[status,setStatus]=useState('INITIALIZING V2 GOVERNANCE READER');const[error,setError]=useState('');const[tab,setTab]=useState('ledger');
 async function refresh(){if(!contractAddress){setStatus('AWAITING V2 DEPLOYMENT');return}try{setData(await loadGovernance());setError('');setStatus('GOVERNANCE STATE VERIFIED')}catch(e){setError(String(e));setStatus('READ FAILED')}}useEffect(()=>{void refresh()},[]);
 async function run(method:string,args:(string|number|boolean)[]){if(!wallet)throw new Error('Connect wallet first.');setStatus(`AWAITING ${method.toUpperCase()}`);try{const hash=await write(method,args,wallet);setStatus(`FINALIZED ${short(hash)}`);await refresh()}catch(e){setError(String(e));setStatus('TRANSACTION BLOCKED');throw e}}
 return <><header><a className="brand" href="#"><img className="brand-logo" src="/mandate-glass-logo.png" alt="Mandate Glass"/><span><b>Mandate Glass</b><small>Enforced DAO disclosure gate</small></span></a><nav>{['ledger','authority','proposal','review'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav><button className="wallet" onClick={()=>connect().then(setWallet).catch(e=>setError(String(e)))}>{wallet?short(wallet):'Connect wallet'}</button></header><div className="ticker"><span>STUDIONET / PROTOCOL V2</span><span>{status}</span><span>{contractAddress?short(contractAddress):'REDEPLOY REQUIRED'}</span></div><main>{error&&<div className="error">{error}<button onClick={()=>void refresh()}>Retry read</button></div>}{tab==='ledger'&&<Ledger data={data}/>} {tab==='authority'&&<Authority run={run}/>} {tab==='proposal'&&<ProposalForm run={run}/>} {tab==='review'&&<ReviewDesk data={data} run={run}/>}</main><footer>DAO authority · canonical source · scoped atomic vote</footer></>}
function Ledger({data}:{data:Data|null}){return <section className="home"><p className="eyebrow">Governance enforcement desk / protocol v2</p><h1>Disclosure is now<br/><i>part of the vote.</i></h1><p className="lede">DAO-controlled sources, proposal-bound reviews, and an authorization consumed atomically with the recorded governance action.</p><div className="metrics"><article><b>{data?.counts.daos??'—'}</b><span>registered DAOs</span></article><article><b>{data?.counts.reviews??'—'}</b><span>bound reviews</span></article><article><b>{data?.counts.votes??'—'}</b><span>guarded votes</span></article></div><div className="table">{data?.reviews.slice().reverse().map(r=><div className="row" key={r.review_id}><b>#{r.review_id}</b><span>Proposal #{r.proposal_id}<small>{short(r.delegate)}</small></span><span>{verdicts[r.verdict]}</span><em className={`state s${r.state}`}>{states[r.state]}</em></div>)}</div></section>}
function Authority({run}:{run:any}){const[f,set]=useState({authority:'',repo:'',proposal:'proposal.json',registry:'affiliations.json',disclosure:'disclosure.json',policy:'Active relationships to proposal recipients must be disclosed.'});return <section><p className="eyebrow">Contract owner only</p><h1 className="page-title">Register DAO authority</h1><form className="paper-form" onSubmit={e=>{e.preventDefault();void run('register_dao',[f.authority,f.repo,f.proposal,f.registry,f.disclosure,f.policy])}}><Input label="DAO / governance authority" value={f.authority} onChange={(e:any)=>set({...f,authority:e.target.value})}/><Input label="Canonical GitHub repository" value={f.repo} onChange={(e:any)=>set({...f,repo:e.target.value})}/><div className="three"><Input label="Proposal path" value={f.proposal} onChange={(e:any)=>set({...f,proposal:e.target.value})}/><Input label="Registry path" value={f.registry} onChange={(e:any)=>set({...f,registry:e.target.value})}/><Input label="Disclosure path" value={f.disclosure} onChange={(e:any)=>set({...f,disclosure:e.target.value})}/></div><Input label="Policy" value={f.policy} onChange={(e:any)=>set({...f,policy:e.target.value})}/><button className="primary">Register authority-controlled source</button></form></section>}
function ProposalForm({run}:{run:any}){const[f,set]=useState({dao:'1',external:'',commit:'',action:'',deadline:''});return <section><p className="eyebrow">DAO authority only</p><h1 className="page-title">Bind an on-chain proposal</h1><form className="paper-form" onSubmit={e=>{e.preventDefault();void run('register_proposal',[Number(f.dao),f.external,f.commit,f.action,Math.floor(new Date(f.deadline).getTime()/1000)])}}><div className="two"><Input label="DAO ID" value={f.dao} onChange={(e:any)=>set({...f,dao:e.target.value})}/><Input label="Governance proposal identity" value={f.external} onChange={(e:any)=>set({...f,external:e.target.value})}/></div><Input label="Locked Git commit" value={f.commit} onChange={(e:any)=>set({...f,commit:e.target.value})}/><Input label="Target action SHA-256" placeholder="sha256:…" value={f.action} onChange={(e:any)=>set({...f,action:e.target.value})}/><Input label="Voting expiry" type="datetime-local" value={f.deadline} onChange={(e:any)=>set({...f,deadline:e.target.value})}/><button className="primary">Register scoped proposal</button></form></section>}
function ReviewDesk({data,run}:{data:Data|null;run:any}){const[pid,setPid]=useState('1');const[delegate,setDelegate]=useState('');return <section><p className="eyebrow">Bound delegate workflow</p><h1 className="page-title">Review, authorize, vote</h1><form className="paper-form" onSubmit={e=>{e.preventDefault();void run('create_review',[Number(pid),delegate])}}><div className="two"><Input label="Proposal ID" value={pid} onChange={(e:any)=>setPid(e.target.value)}/><Input label="Delegate (must equal connected wallet)" value={delegate} onChange={(e:any)=>setDelegate(e.target.value)}/></div><button className="primary">Open bound review</button></form><div className="table">{data?.reviews.slice().reverse().map(r=>{const p=data.proposals.find(x=>x.proposal_id===r.proposal_id);return <div className="review-card" key={r.review_id}><b>Review #{r.review_id} · {verdicts[r.verdict]||states[r.state]}</b><code>{r.authorization_scope||'No authorization scope issued'}</code><div className="actions">{(r.state===1||r.state===5)&&<button className="primary" onClick={()=>void run(r.state===5?'retry_review':'evaluate_review',[r.review_id,r.revision])}>{r.state===5?'Retry canonical evidence':'Evaluate'}</button>}{r.state===2&&r.verdict<3&&<button className="primary" onClick={()=>void run('authorize_result',[r.review_id,r.revision])}>Issue scoped authorization</button>}{p&&mayExecute(r,p,Math.floor(Date.now()/1000))&&<><button className="primary" onClick={()=>void run('execute_vote',[r.review_id,r.revision,p.action_digest,true])}>Vote FOR atomically</button><button className="quiet" onClick={()=>void run('execute_vote',[r.review_id,r.revision,p.action_digest,false])}>Vote AGAINST</button></>}</div></div>})}</div></section>}
