export type Counts={daos:number;proposals:number;reviews:number;votes:number};
export type Dao={dao_id:number;authority:string;repository:string;proposal_path:string;registry_path:string;disclosure_path:string;policy:string;revision:number;active:boolean};
export type Proposal={proposal_id:number;dao_id:number;external_id:string;snapshot_commit:string;action_digest:string;deadline:string;revision:number;open:boolean};
export type Review={review_id:number;proposal_id:number;dao_id:number;delegate:string;state:number;revision:number;retry_count:number;verdict:number;reason:string;evidence_digest:string;match_count:number;authorization_consumed:number;authorization_scope:string};
export type Vote={vote_id:number;review_id:number;proposal_id:number;delegate:string;support:boolean;action_digest:string;created_at:string};
const address=import.meta.env.VITE_CONTRACT_ADDRESS?.trim();let sdkPromise:Promise<any>|null=null;let clientPromise:Promise<any>|null=null;
async function sdk(){if(!sdkPromise)sdkPromise=Promise.all([import('genlayer-js'),import('genlayer-js/chains'),import('genlayer-js/types')]).then(([core,chains,types])=>({createClient:core.createClient,studionet:chains.studionet,TransactionStatus:types.TransactionStatus}));return sdkPromise;}
async function reader(){if(!clientPromise)clientPromise=sdk().then(({createClient,studionet})=>createClient({chain:studionet}));return clientPromise;}
export const contractAddress=address||'';
function requireAddress(){if(!/^0x[0-9a-fA-F]{40}$/.test(contractAddress))throw new Error('Verified v2 contract address is not configured.');return contractAddress as `0x${string}`;}
export async function read<T>(functionName:string,args:(string|number)[]=[]):Promise<T>{const client=await reader();return await client.readContract({address:requireAddress(),functionName,args,jsonSafeReturn:true}) as T;}
export async function loadGovernance(){const [protocol,counts]=await Promise.all([read<any>('get_protocol'),read<Counts>('get_counts')]);if(protocol?.name!=='MandateGlassGovernanceGate'||protocol?.version!==2)throw new Error('Contract identity or protocol version mismatch.');const daos=await Promise.all(Array.from({length:counts.daos},(_,i)=>read<Dao>('get_dao',[i+1])));const proposals=await Promise.all(Array.from({length:counts.proposals},(_,i)=>read<Proposal>('get_proposal',[i+1])));const reviews=await Promise.all(Array.from({length:counts.reviews},(_,i)=>read<Review>('get_review',[i+1])));const votes=await Promise.all(Array.from({length:counts.votes},(_,i)=>read<Vote>('get_vote',[i+1])));return{counts,daos,proposals,reviews,votes};}
async function wallet(){const provider=(window as any).ethereum;if(!provider?.request)throw new Error('Install a compatible browser wallet.');const accounts=await provider.request({method:'eth_requestAccounts'});const account=accounts?.[0];if(!/^0x[0-9a-fA-F]{40}$/.test(account||''))throw new Error('Wallet returned no valid account.');const{createClient,studionet}=await sdk();await createClient({chain:studionet,provider,account}).connect('studionet');return{provider,account};}
export async function connect(){return(await wallet()).account as string;}
export async function write(functionName:string,args:(string|number|boolean)[],expected:string){const{provider,account}=await wallet();if(account.toLowerCase()!==expected.toLowerCase())throw new Error('Wallet account changed. Reconnect before signing.');const{createClient,studionet,TransactionStatus}=await sdk();const client=await reader();const hash=await createClient({chain:studionet,provider,account}).writeContract({address:requireAddress(),functionName,args,value:0n});if(!/^0x[0-9a-fA-F]{64}$/.test(hash))throw new Error('No valid transaction hash returned.');const receipt:any=await client.waitForTransactionReceipt({hash,status:TransactionStatus.FINALIZED,interval:4000,retries:120});const leader=receipt?.consensus_data?.leader_receipt;const list=(Array.isArray(leader)?leader:leader?[leader]:[]).filter((x:any)=>x.vote!=='idle');if(!list.length||list.some((x:any)=>x.execution_result!=='SUCCESS'))throw new Error(`Finalized execution failed. Inspect ${hash}.`);return hash as string;}
